### ISSUE TITLE
Get request JSON  is not outputting based on template

### ISSUE THREAD

**Issue by TheEducational** [stefanman125/simple-tasks#4]
When you do a simple GET request using curl/browser, the JSON output of the collection is not in order
![image](https://github.com/stefanman125/simple-tasks/assets/10445026/59954acf-0f3a-4a2e-bc47-5c364cfa8eb9)

**Comment by stefanman125** [comment]
Hmm, I feel like this shouldn't be a problem when parsing the JSON in general, but I guess it wouldn't hurt to have some consistency. Will look into it.

**Comment by stefanman125** [comment]
Fixed in c1305bb8918b747713d681201090f9f036797a2c
