### ISSUE TITLE
Cannot add multiple tasks to the collection

### ISSUE THREAD

**Issue by TheEducational** [stefanman125/simple-tasks#5]
When you try to add a second item to the collection, ist prompting you with "Collection Already Exists"

E.g I have a task ID 1 in collection A. When i POST with task ID 2 its does not add it.
![image](https://github.com/stefanman125/simple-tasks/assets/10445026/62b85124-f733-4d86-a1ab-0ae315aef5a2)

To Reproduce
 Post 1 entry
change the ID
Try to Post Again

**Comment by stefanman125** [comment]
Need to use PUT method when updating task collections.

![image](https://github.com/stefanman125/simple-tasks/assets/38778523/a2bfdfbe-1bdd-464a-b703-50852ec1ae39)
